version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
        - 5602:5602
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  httpd:
    image: httpd:2.4
    container_name: httpd
    ports:
        - 80:80
    volumes: 
        - ./www/html/:/usr/local/apache2/htdocs/
