---
version: '3.6'
services:
  # Setup Elasticsearch
  #   * keystore
  #   * SSL
  setup_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: setup_elasticsearch
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-elasticsearch.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    volumes:
      - './config:/config'
      - './scripts/setup-elasticsearch.sh:/usr/local/bin/setup-elasticsearch.sh:ro'

  setup_kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: setup_kibana
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    volumes:
      - './config:/config'
      - './scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro'
      - './config/ssl/ca/ca.crt:/usr/share/kibana/config/ca/ca.crt'
    depends_on: ['elasticsearch']
    networks: ['stack']

